### ISSUE TITLE
Kawa: fecore0-KAWA fail

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#128]
```java
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class gnu.lists.Pair (java.lang.Boolean is in module java.base of loader 'bootstrap'; gnu.lists.Pair is in unnamed module of loader 'app')
        at kawa.lib.lists.cadr(lists.scm:67)
        at atInteractiveLevel-52.run(fecore0.sps:6)
        at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:290)
        at gnu.expr.ModuleExp.evalModule(ModuleExp.java:211)
        at kawa.Shell.run(Shell.java:289)
        at kawa.Shell.runFile(Shell.java:551)
        at kawa.standard.load.apply2(load.java:67)
        at kawa.standard.load.apply1(load.java:27)
        at atInteractiveLevel-12.$Pc$PcSelfbootLoadProgram(selfboot-prog.scm:111)
        at atInteractiveLevel-12.$Pc$PcSelfbootLoadProgram$check(selfboot-prog.scm:111)
        at gnu.mapping.Procedure.applyToConsumerDefault(Procedure.java:75)
        at gnu.mapping.CallContext.runUntilDone(CallContext.java:586)
        at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:343)
        at gnu.expr.ModuleExp.evalModule(ModuleExp.java:211)
        at kawa.Shell.run(Shell.java:289)
        at kawa.Shell.runFile(Shell.java:551)
        at kawa.standard.load.apply2(load.java:67)
        at kawa.standard.load.apply1(load.java:27)
        at gnu.mapping.Procedure1or2.applyToObject(Procedure1or2.java:64)
        at gnu.mapping.Procedure.applyToConsumerDefault(Procedure.java:75)
        at gnu.mapping.CallContext.runUntilDone(CallContext.java:586)
        at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:343)
        at gnu.expr.ModuleExp.evalModule(ModuleExp.java:211)
        at kawa.Shell.run(Shell.java:289)
        at kawa.Shell.runFile(Shell.java:551)
        at kawa.standard.load.apply2(load.java:67)
        at kawa.standard.load.apply1(load.java:27)
        at gnu.mapping.Procedure1or2.applyToObject(Procedure1or2.java:64)
        at gnu.mapping.Procedure.applyToConsumerDefault(Procedure.java:75)
        at gnu.mapping.CallContext.runUntilDone(CallContext.java:586)
        at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:343)
        at gnu.expr.CompiledModule.evalModule(CompiledModule.java:42)
        at gnu.expr.CompiledModule.evalModule(CompiledModule.java:60)
        at kawa.Shell.runFile(Shell.java:571)
        at kawa.Shell.runFileOrClass(Shell.java:474)
        at kawa.repl.processArgs(repl.java:710)
        at kawa.repl.main(repl.java:830)

```

Related: https://github.com/okuoku/yuni/issues/127
Test disabled: https://github.com/okuoku/yuni/commit/378954b8b0d9bcd03de2d3baa1e5726aca50eea7

~~Need our own `command-line` to work.~~ It seems like a pure frontend issue.

**Comment by okuoku** [comment]
Watching: https://github.com/okuoku/yuni/blob/cd7638cc2c6c5d7174a9ae2ebff3d874ca80a4db/tests/fails.cmake#L54
