### ISSUE TITLE
Kawa: java.lang.IllegalArgumentException: Expected scheme name at index 0

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#23]
It seems Kawa does not handle `include`ed source properly..

```
java.lang.IllegalArgumentException: Expected scheme name at index 0: :.
        at java.net.URI.create(Unknown Source)
        at java.net.URI.resolve(Unknown Source)
        at gnu.kawa.io.FilePath.resolve(FilePath.java:270)
        at kawa.standard.Include.process(Include.java:75)
        at kawa.standard.Include.scanForm(Include.java:34)
        at kawa.standard.define_library.scanModulePass(define_library.java:124)
        at kawa.standard.define_library.scanForm(define_library.java:27)
        at kawa.lang.Translator.scanForm(Translator.java:1508)
        at gnu.kawa.lispexpr.LispLanguage.parse(LispLanguage.java:82)
        at gnu.expr.Compilation.process(Compilation.java:1935)
        at gnu.expr.ModuleInfo.loadEager(ModuleInfo.java:317)
        at kawa.standard.require.importDefinitions(require.java:279)
        at kawa.standard.ImportFromLibrary.handleImport(ImportFromLibrary.java:408)
        at kawa.standard.ImportFromLibrary.scanImportSet(ImportFromLibrary.java:222)
        at kawa.standard.ImportFromLibrary.scanForm(ImportFromLibrary.java:93)
        at kawa.lang.Translator.scanForm(Translator.java:1508)
        at gnu.kawa.lispexpr.LispLanguage.parse(LispLanguage.java:101)
        at gnu.expr.Language.parse(Language.java:755)
        at kawa.Shell.run(Shell.java:262)
        at kawa.Shell.runFile(Shell.java:523)
        at kawa.standard.load.apply2(load.java:67)
        at kawa.standard.load.apply1(load.java:27)
        at gnu.mapping.Procedure.apply(Procedure.java:135)
        at gnu.mapping.Procedure.apply(Procedure.java:118)
        at gnu.mapping.CallContext.runUntilDone(CallContext.java:234)
        at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:381)
        at gnu.expr.ModuleExp.evalModule(ModuleExp.java:219)
        at kawa.Shell.run(Shell.java:291)
        at kawa.Shell.runFile(Shell.java:523)
        at kawa.Shell.runFileOrClass(Shell.java:447)
        at kawa.repl.processArgs(repl.java:286)
        at kawa.repl.main(repl.java:871)
Caused by: java.net.URISyntaxException: Expected scheme name at index 0: :.
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.failExpecting(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
```

**Comment by okuoku** [comment]
We gave up `shorten`. WONTFIX.
