### ISSUE TITLE
Kawa: Cannot load Alexpander

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#85]
https://ci.appveyor.com/project/okuoku/yuni/build/0.PRE.159/job/urs3j5f4g172909v#L2588

```java
Exception in thread "main" java.lang.Error: attempting to push dead variable
	at gnu.bytecode.CodeAttr.emitLoad(CodeAttr.java:1388)
	at gnu.expr.LambdaExp.compile(LambdaExp.java:814)
	at gnu.expr.Expression.compileWithPosition(Expression.java:143)
	at gnu.expr.Expression.compileWithPosition(Expression.java:126)
	at gnu.expr.PrimProcedure.compileArgs(PrimProcedure.java:612)
	at gnu.expr.PrimProcedure.compile(PrimProcedure.java:742)
	at gnu.expr.ApplyExp.compile(ApplyExp.java:317)
	at gnu.expr.ApplyExp.compile(ApplyExp.java:192)
	at gnu.expr.Expression.compileWithPosition(Expression.java:143)
	at gnu.expr.Expression.compileWithPosition(Expression.java:126)
	at gnu.expr.LambdaExp.compileAsInlined(LambdaExp.java:1563)
	at gnu.expr.ApplyExp.compile(ApplyExp.java:398)
	at gnu.expr.ApplyExp.compile(ApplyExp.java:192)
	at gnu.expr.Expression.compileWithPosition(Expression.java:143)
	at gnu.expr.Expression.compileWithPosition(Expression.java:126)
	at gnu.expr.LetExp.compile(LetExp.java:166)
	at gnu.expr.Expression.compileWithPosition(Expression.java:143)
```

**Comment by okuoku** [comment]
Invoke branch has a bit different result:

https://travis-ci.org/okuoku/yuni/jobs/232988261#L339
```java
Exception in thread "main" java.lang.IllegalAccessError: no such method: yuniexternal.alexpander$frame4.lambda23exprAssert$check(Procedure,CallContext)Object/invokeStatic
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483)
	at yuniexternal.alexpander.<clinit>(alexpander.sld)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at gnu.expr.ModuleInfo.setupModuleExp(ModuleInfo.java:169)
	at kawa.standard.require.importDefinitions(require.java:310)
	at kawa.standard.ImportFromLibrary.handleImport(ImportFromLibrary.java:478)
	at kawa.standard.ImportFromLibrary.scanImportSet(ImportFromLibrary.java:291)
	at kawa.standard.ImportFromLibrary.scanForm(ImportFromLibrary.java:95)
	at kawa.standard.define_library.scanModulePass(define_library.java:124)
	at kawa.standard.define_library.scanForm(define_library.java:27)
	at kawa.lang.Translator.scanForm(Translator.java:1608)
	at gnu.kawa.lispexpr.LispLanguage.parse(LispLanguage.java:89)
```

**Comment by okuoku** [comment]
Reported: https://gitlab.com/kashell/Kawa/issues/11

Test disabled: https://github.com/okuoku/yuni/commit/89885d6a547c5509e114c4374eef376857238af3

**Comment by okuoku** [comment]
https://gitlab.com/kashell/Kawa/commit/777845681ddb48fa774db9707b74fd5e7d7ab516 fixes inliner problem. 

miniread doesn't work yet.

**Comment by okuoku** [comment]
Recent Kawa can run miniread. Perhaps it fixed in somewhere.
