### ISSUE TITLE
Kawa: Does not pass vmtest6 on Windows

### ISSUE THREAD

**Issue by okuoku** [okuoku/yuni#98]
https://ci.appveyor.com/project/okuoku/yuni/branch/master/job/emw7wa6cwxi2c9nl

```
35/55 Test #35: KAWA-vmtest6.sps ....................***Failed    1.00 sec
-> RUN: "C:/projects/yuni/tests/vm/vmtest6.sps" 
-> LOOKUP: (yuni scheme) 
-> TRYING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/yuni/scheme.sld" 
-> READING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/yuni/scheme.sld" 
-> PROC: ((yuni-runtime r7rs) (yuni compat scheme)) 
-> LOOKUP: (yuni compat scheme) 
-> TRYING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/yuni/compat/scheme.sld" 
-> READING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/yuni/compat/scheme.sld" 
-> PROC: ((r7rs-common-yuni compat scheme)) 
-> LOOKUP: (r7rs-common-yuni compat scheme) 
-> TRYING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/r7rs-common-yuni/compat/scheme.sld" 
-> READING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/r7rs-common-yuni/compat/scheme.sld" 
-> PROC: ((yuni-runtime r7rs) (scheme base) (scheme case-lambda) (scheme cxr)
          (scheme file) (scheme inexact) (scheme process-context) (scheme read)
          (scheme write)) 
-> LOADING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/r7rs-common-yuni/compat/scheme.sld" 
-> LOADING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/yuni/compat/scheme.sld" 
-> LOADING: "\\projects\\yuni\\work\\bootstrap\\lib-stub\\kawa/yuni/scheme.sld" 
java.nio.file.FileSystemException: testfile.bin: The process cannot access the file because it is being used by another process.
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at gnu.kawa.io.FilePath.deleteFile(FilePath.java:129)
	at kawa.lib.files.deleteFile(files.scm:113)
	at atInteractiveLevel-14.clearFile(vmtest6.sps:46)
	at atInteractiveLevel-14.apply1(vmtest6.sps:44)
	at gnu.expr.ModuleMethod.apply1(ModuleMethod.java:213)
	at atInteractiveLevel-16.testfilesRemove(vmtest6.sps:57)
	at atInteractiveLevel-16.apply0(vmtest6.sps:56)
	at gnu.expr.ModuleMethod.apply0(ModuleMethod.java:207)
	at gnu.expr.ModuleMethod.apply(ModuleMethod.java:181)
	at gnu.mapping.CallContext.runUntilDone(CallContext.java:227)
	at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:350)
	at gnu.expr.ModuleExp.evalModule(ModuleExp.java:212)
	at kawa.Shell.run(Shell.java:283)
	at kawa.Shell.runFile(Shell.java:545)
	at kawa.standard.load.apply2(load.java:67)
	at kawa.standard.load.apply1(load.java:27)
	at projects.yuni.yuniloader.yuniloader-kawa.run(yuniloader-kawa.scm:119)
	at projects.yuni.yuniloader.yuniloader-kawa.apply1(yuniloader-kawa.scm:35)
	at gnu.expr.ModuleMethod.apply1(ModuleMethod.java:213)
	at gnu.expr.ModuleMethod.apply(ModuleMethod.java:184)
	at gnu.mapping.CallContext.runUntilDone(CallContext.java:227)
	at projects.yuni.yuniloader.yuniloader-kawa.run(yuniloader-kawa.scm:139)
	at gnu.expr.ModuleExp.evalModule2(ModuleExp.java:293)
	at gnu.expr.CompiledModule.evalModule(CompiledModule.java:42)
	at gnu.expr.CompiledModule.evalModule(CompiledModule.java:60)
	at kawa.Shell.runFile(Shell.java:565)
	at kawa.Shell.runFileOrClass(Shell.java:468)
	at kawa.repl.processArgs(repl.java:700)
	at kawa.repl.main(repl.java:820)
CMake Error at C:/projects/yuni/tests/yunibase/runwithcleandir.cmake:43 (message):
  Unexpected: -1
```

As Kawa on Linux is OK, so it seems Kawa does not close the file immediately on `close-port`.

Test disabled: https://github.com/okuoku/yuni/commit/1f0fa2b382c03c3dfbaaa04c4543d9679060c199

**Comment by okuoku** [comment]
Removed vmtest6 and we're no longer support build issues. Won't fix.
